name: Android Build

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:


jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
    # Проверка репозитория
    - name: Checkout repository
      uses: actions/checkout@v4
    # Установка Python и зависимостей
    - name: Installing Python and dependencies
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        # architecture: x64        
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt        
    - name: Install Cython
      run: 
        pip install Cython
    # Установка Android SDK и NDK и принятие лицензий
    - name: Setup Android SDK and NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk unzip wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        sdkmanager --sdk_root=$ANDROID_HOME --licenses
        sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;23.1.7779620"


      
    # Сборка APK
    - name: Build APK
      run: |
        buildozer -v android debug
        # ls bin/ # Проверка наличия APK

    # Сохранение APK как артефакта
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk
