name: Android Build

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:


jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
    # Проверка репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Установка Python и зависимостей
    - name: Installing Python and dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        # architecture: x64

    - name: Install dependencies
      run: |
          pip install -r requirements.txt
          pip install --upgrade Cython==0.29.33 virtualenv


    # Сборка APK
    - name: Build APK
      run: |
        buildozer -v android debug
        ls bin/ # Проверка наличия APK

    # Сохранение APK как артефакта
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk
